# Real Estate Price Prediction Project

## Importing the necessary bibliotheca

In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd

## Load the Data

In [6]:
data = pd.read_csv('belgian_property_prices.csv')

data.head()

,as_built_plan,available_as_of,basement,bathrooms,bedroom_1_surface,bedroom_2_surface,bedroom_3_surface,bedrooms,building_condition,co2_emission,...,width_of_the_lot_on_the_street,yearly_theoretical_total_energy_consumption,housenumber,street,city,postal,state,lat,lng,price
0,0.0,After signing the deed,1.0,1.0,12.0,10.0,10.0,3.0,Good,9802.0,...,11.0,NaN,30,Stationsstraat,Ronse,9600.0,Vlaams Gewest,50.743367,3.601306,275000
1,0.0,After signing the deed,1.0,1.0,15.0,11.0,11.0,4.0,Good,NaN,...,NaN,NaN,52,Wingenesteenweg,Wingene,8750.0,Vlaams Gewest,51.042146,3.302600,430000
2,NaN,After signing the deed,1.0,3.0,22.0,22.0,22.0,5.0,As new,NaN,...,6.0,NaN,157,Mechelsesteenweg,Antwerpen,2018.0,Vlaams Gewest,51.205030,4.410943,949000
3,0.0,NaN,NaN,3.0,33.0,30.0,23.0,5.0,As new,NaN,...,19.0,NaN,66,Noordzandstraat,Brugge,8000.0,Vlaams Gewest,51.206826,3.219186,2200000
4,0.0,After signing the deed,NaN,NaN,19.0,NaN,NaN,1.0,Just renovated,58.0,...,5.0,24263.0,15,Rue de l'Etoile,Wavre,1301.0,Région Wallonne,50.717062,4.577550,195000

## Exploratory Data Analysis, EDA

In [7]:
data.info()

data.describe()

data.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4770 entries, 0 to 4769
Data columns (total 54 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   as_built_plan                                   2389 non-null   float64
 1   available_as_of                                 3912 non-null   object
 2   basement                                        2083 non-null   float64
 3   bathrooms                                       4523 non-null   float64
 4   bedroom_1_surface                               3163 non-null   float64
 5   bedroom_2_surface                               3105 non-null   float64
 6   bedroom_3_surface                               2623 non-null   float64
 7   bedrooms                                        4740 non-null   float64
 8   building_condition                              4485 non-null   object
 9   co2_emission                                    1937 non-null   float64
 10  cadastral_income                                3692 non-null   float64
 11  connection_to_sewer_network                     2030 non-null   float64
 12  construction_year                               3444 non-null   float64
 13  covered_parking_spaces                          2718 non-null   float64
 14  dining_room                                     1339 non-null   float64
 15  double_glazing                                  4119 non-null   float64
 16  energy_class                                    4770 non-null   object
 17  external_reference                              4332 non-null   object
 18  flood_zone_type                                 2783 non-null   float64
 19  furnished                                       2109 non-null   float64
 20  garden_surface                                  2181 non-null   float64
 21  gas_water__electricity                          3224 non-null   float64
 22  heating_type                                    4136 non-null   object
 23  kitchen_surface                                 2675 non-null   float64
 24  kitchen_type                                    3960 non-null   object
 25  latest_land_use_designation                     2245 non-null   object
 26  living_area                                     4702 non-null   float64
 27  living_room_surface                             3015 non-null   float64
 28  number_of_frontages                             4455 non-null   float64
 29  office                                          1444 non-null   float64
 30  outdoor_parking_spaces                          2355 non-null   float64
 31  planning_permission_obtained                    1540 non-null   float64
 32  possible_priority_purchase_right                2198 non-null   float64
 33  primary_energy_consumption                      4571 non-null   float64
 34  proceedings_for_breach_of_planning_regulations  1742 non-null   float64
 35  reference_number_of_the_epc_report              4770 non-null   object
 36  street_frontage_width                           2096 non-null   float64
 37  subdivision_permit                              1814 non-null   float64
 38  surface_of_the_plot                             4563 non-null   float64
 39  surroundings_type                               2274 non-null   object
 40  tv_cable                                        1460 non-null   float64
 41  tenement_building                               4723 non-null   float64
 42  toilets                                         4348 non-null   float64
 43  website                                         3963 non-null   object
 44  width_of_the_lot_on_the_street                  1990 non-null   float64
 45  yearly_theoretical_total_energy_consumption     1813 non-null   float64
 46  housenumber                                     4657 non-null   object
 47  street                                          4685 non-null   object
 48  city                                            4721 non-null   object
 49  postal                                          4737 non-null   float64
 50  state                                           4728 non-null   object
 51  lat                                             4737 non-null   float64
 52  lng                                             4737 non-null   float64
 53  price                                           4770 non-null   int64
dtypes: float64(39), int64(1), object(14)
memory usage: 2.0+ MB

Index(['as_built_plan', 'available_as_of', 'basement', 'bathrooms',
       'bedroom_1_surface', 'bedroom_2_surface', 'bedroom_3_surface',
       'bedrooms', 'building_condition', 'co2_emission', 'cadastral_income',
       'connection_to_sewer_network', 'construction_year',
       'covered_parking_spaces', 'dining_room', 'double_glazing',
       'energy_class', 'external_reference', 'flood_zone_type', 'furnished',
       'garden_surface', 'gas_water__electricity', 'heating_type',
       'kitchen_surface', 'kitchen_type', 'latest_land_use_designation',
       'living_area', 'living_room_surface', 'number_of_frontages', 'office',
       'outdoor_parking_spaces', 'planning_permission_obtained',
       'possible_priority_purchase_right', 'primary_energy_consumption',
       'proceedings_for_breach_of_planning_regulations',
       'reference_number_of_the_epc_report', 'street_frontage_width',
       'subdivision_permit', 'surface_of_the_plot', 'surroundings_type',
       'tv_cable', 'tenement_building', 'toilets', 'website',
       'width_of_the_lot_on_the_street',
       'yearly_theoretical_total_energy_consumption', 'housenumber', 'street',
       'city', 'postal', 'state', 'lat', 'lng', 'price'],
      dtype='object')

## Setting target variables

In [8]:
y = data['price']

X = data[['bedrooms', 'bathrooms', 'living_area', 'surface_of_the_plot', 'postal']]

## Fill in missing values

In [10]:
X = X.fillna(X.median())

## Linear Regression Modell

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

# Prediction test set
y_pred = model.predict(X_test)

# Calculate error
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R²): {r2}")

Mean Squared Error (MSE): 276733997805.45746
R-squared (R²): 0.36413580934979217

## Coefficients

In [11]:
coefficients = pd.DataFrame(model.coef_, X.columns, columns=['Coefficient'])
coefficients

                       Coefficient
bedrooms             -23068.190514
bathrooms            157722.473485
living_area            1785.162403
surface_of_the_plot      14.711765
postal                   -9.299007