# Real Estate Price Prediction Project

## Importing the necessary bibliotheca

In [73]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd
import pickle

## Load the Data

In [74]:
#data = pd.read_csv('belgian_property_prices.csv')
data = pd.read_csv('../raw_data/belgian_property_prices.csv')
#data = pd.read_csv('raw_data/belgian_property_prices.csv')
data.head()

,as_built_plan,available_as_of,basement,bathrooms,bedroom_1_surface,bedroom_2_surface,bedroom_3_surface,bedrooms,building_condition,co2_emission,...,width_of_the_lot_on_the_street,yearly_theoretical_total_energy_consumption,housenumber,street,city,postal,state,lat,lng,price
0,0.0,After signing the deed,1.0,1.0,12.0,10.0,10.0,3.0,Good,9802.0,...,11.0,NaN,30,Stationsstraat,Ronse,9600.0,Vlaams Gewest,50.743367,3.601306,275000
1,0.0,After signing the deed,1.0,1.0,15.0,11.0,11.0,4.0,Good,NaN,...,NaN,NaN,52,Wingenesteenweg,Wingene,8750.0,Vlaams Gewest,51.042146,3.302600,430000
2,NaN,After signing the deed,1.0,3.0,22.0,22.0,22.0,5.0,As new,NaN,...,6.0,NaN,157,Mechelsesteenweg,Antwerpen,2018.0,Vlaams Gewest,51.205030,4.410943,949000
3,0.0,NaN,NaN,3.0,33.0,30.0,23.0,5.0,As new,NaN,...,19.0,NaN,66,Noordzandstraat,Brugge,8000.0,Vlaams Gewest,51.206826,3.219186,2200000
4,0.0,After signing the deed,NaN,NaN,19.0,NaN,NaN,1.0,Just renovated,58.0,...,5.0,24263.0,15,Rue de l'Etoile,Wavre,1301.0,Région Wallonne,50.717062,4.577550,195000

## Exploratory Data Analysis, EDA

In [75]:
data.info()

data.describe()

data.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4770 entries, 0 to 4769
Data columns (total 54 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   as_built_plan                                   2389 non-null   float64
 1   available_as_of                                 3912 non-null   object
 2   basement                                        2083 non-null   float64
 3   bathrooms                                       4523 non-null   float64
 4   bedroom_1_surface                               3163 non-null   float64
 5   bedroom_2_surface                               3105 non-null   float64
 6   bedroom_3_surface                               2623 non-null   float64
 7   bedrooms                                        4740 non-null   float64
 8   building_condition                              4485 non-null   object
 9   co2_emission                                    1937 non-null   float64
 10  cadastral_income                                3692 non-null   float64
 11  connection_to_sewer_network                     2030 non-null   float64
 12  construction_year                               3444 non-null   float64
 13  covered_parking_spaces                          2718 non-null   float64
 14  dining_room                                     1339 non-null   float64
 15  double_glazing                                  4119 non-null   float64
 16  energy_class                                    4770 non-null   object
 17  external_reference                              4332 non-null   object
 18  flood_zone_type                                 2783 non-null   float64
 19  furnished                                       2109 non-null   float64
 20  garden_surface                                  2181 non-null   float64
 21  gas_water__electricity                          3224 non-null   float64
 22  heating_type                                    4136 non-null   object
 23  kitchen_surface                                 2675 non-null   float64
 24  kitchen_type                                    3960 non-null   object
 25  latest_land_use_designation                     2245 non-null   object
 26  living_area                                     4702 non-null   float64
 27  living_room_surface                             3015 non-null   float64
 28  number_of_frontages                             4455 non-null   float64
 29  office                                          1444 non-null   float64
 30  outdoor_parking_spaces                          2355 non-null   float64
 31  planning_permission_obtained                    1540 non-null   float64
 32  possible_priority_purchase_right                2198 non-null   float64
 33  primary_energy_consumption                      4571 non-null   float64
 34  proceedings_for_breach_of_planning_regulations  1742 non-null   float64
 35  reference_number_of_the_epc_report              4770 non-null   object
 36  street_frontage_width                           2096 non-null   float64
 37  subdivision_permit                              1814 non-null   float64
 38  surface_of_the_plot                             4563 non-null   float64
 39  surroundings_type                               2274 non-null   object
 40  tv_cable                                        1460 non-null   float64
 41  tenement_building                               4723 non-null   float64
 42  toilets                                         4348 non-null   float64
 43  website                                         3963 non-null   object
 44  width_of_the_lot_on_the_street                  1990 non-null   float64
 45  yearly_theoretical_total_energy_consumption     1813 non-null   float64
 46  housenumber                                     4657 non-null   object
 47  street                                          4685 non-null   object
 48  city                                            4721 non-null   object
 49  postal                                          4737 non-null   float64
 50  state                                           4728 non-null   object
 51  lat                                             4737 non-null   float64
 52  lng                                             4737 non-null   float64
 53  price                                           4770 non-null   int64
dtypes: float64(39), int64(1), object(14)
memory usage: 2.0+ MB

Index(['as_built_plan', 'available_as_of', 'basement', 'bathrooms',
       'bedroom_1_surface', 'bedroom_2_surface', 'bedroom_3_surface',
       'bedrooms', 'building_condition', 'co2_emission', 'cadastral_income',
       'connection_to_sewer_network', 'construction_year',
       'covered_parking_spaces', 'dining_room', 'double_glazing',
       'energy_class', 'external_reference', 'flood_zone_type', 'furnished',
       'garden_surface', 'gas_water__electricity', 'heating_type',
       'kitchen_surface', 'kitchen_type', 'latest_land_use_designation',
       'living_area', 'living_room_surface', 'number_of_frontages', 'office',
       'outdoor_parking_spaces', 'planning_permission_obtained',
       'possible_priority_purchase_right', 'primary_energy_consumption',
       'proceedings_for_breach_of_planning_regulations',
       'reference_number_of_the_epc_report', 'street_frontage_width',
       'subdivision_permit', 'surface_of_the_plot', 'surroundings_type',
       'tv_cable', 'tenement_building', 'toilets', 'website',
       'width_of_the_lot_on_the_street',
       'yearly_theoretical_total_energy_consumption', 'housenumber', 'street',
       'city', 'postal', 'state', 'lat', 'lng', 'price'],
      dtype='object')

## Preprocessing

In [76]:
import pandas as pd

data = pd.read_csv('../raw_data/belgian_property_prices.csv')

data_raw_backup = data.copy()

data_raw_backup.to_csv('belgian_property_prices_backup.csv', index=False)

data.head()

,as_built_plan,available_as_of,basement,bathrooms,bedroom_1_surface,bedroom_2_surface,bedroom_3_surface,bedrooms,building_condition,co2_emission,...,width_of_the_lot_on_the_street,yearly_theoretical_total_energy_consumption,housenumber,street,city,postal,state,lat,lng,price
0,0.0,After signing the deed,1.0,1.0,12.0,10.0,10.0,3.0,Good,9802.0,...,11.0,NaN,30,Stationsstraat,Ronse,9600.0,Vlaams Gewest,50.743367,3.601306,275000
1,0.0,After signing the deed,1.0,1.0,15.0,11.0,11.0,4.0,Good,NaN,...,NaN,NaN,52,Wingenesteenweg,Wingene,8750.0,Vlaams Gewest,51.042146,3.302600,430000
2,NaN,After signing the deed,1.0,3.0,22.0,22.0,22.0,5.0,As new,NaN,...,6.0,NaN,157,Mechelsesteenweg,Antwerpen,2018.0,Vlaams Gewest,51.205030,4.410943,949000
3,0.0,NaN,NaN,3.0,33.0,30.0,23.0,5.0,As new,NaN,...,19.0,NaN,66,Noordzandstraat,Brugge,8000.0,Vlaams Gewest,51.206826,3.219186,2200000
4,0.0,After signing the deed,NaN,NaN,19.0,NaN,NaN,1.0,Just renovated,58.0,...,5.0,24263.0,15,Rue de l'Etoile,Wavre,1301.0,Région Wallonne,50.717062,4.577550,195000

In [77]:
# Replace missing values for specified columns with the median
for col in ['bedroom_1_surface', 'bedroom_2_surface', 'bedroom_3_surface', 'bathrooms', 'bedrooms']:
    data[col] = data[col].fillna(data[col].median())

In [78]:
print(data.columns)

Index(['as_built_plan', 'available_as_of', 'basement', 'bathrooms',
       'bedroom_1_surface', 'bedroom_2_surface', 'bedroom_3_surface',
       'bedrooms', 'building_condition', 'co2_emission', 'cadastral_income',
       'connection_to_sewer_network', 'construction_year',
       'covered_parking_spaces', 'dining_room', 'double_glazing',
       'energy_class', 'external_reference', 'flood_zone_type', 'furnished',
       'garden_surface', 'gas_water__electricity', 'heating_type',
       'kitchen_surface', 'kitchen_type', 'latest_land_use_designation',
       'living_area', 'living_room_surface', 'number_of_frontages', 'office',
       'outdoor_parking_spaces', 'planning_permission_obtained',
       'possible_priority_purchase_right', 'primary_energy_consumption',
       'proceedings_for_breach_of_planning_regulations',
       'reference_number_of_the_epc_report', 'street_frontage_width',
       'subdivision_permit', 'surface_of_the_plot', 'surroundings_type',
       'tv_cable', 'tenement_building', 'toilets', 'website',
       'width_of_the_lot_on_the_street',
       'yearly_theoretical_total_energy_consumption', 'housenumber', 'street',
       'city', 'postal', 'state', 'lat', 'lng', 'price'],
      dtype='object')

In [79]:
# Make a copy of the DataFrame to avoid chained assignment issues
#data = data.copy()

# Replace missing values in categorical variables with "Unknown"
#data['building_condition'] = data['building_condition'].fillna('Unknown')
#data['state'] = data['state'].fillna('Unknown')

In [80]:
# Convert categorical variables with a few well-defined categories into numerical form using One-Hot Encoding.
# This is particularly suitable for variables like building_condition, state, and possibly city if you don't want to differentiate cities too strongly.
data = pd.get_dummies(data, columns=['building_condition', 'state'], drop_first=True)

In [81]:
# Display the frequency of each category
#condition_counts = data['building_condition'].value_counts(dropna=False)
#print("Category counts in 'building_condition':")
#print(condition_counts)

In [82]:
print(data.columns)

Index(['as_built_plan', 'available_as_of', 'basement', 'bathrooms',
       'bedroom_1_surface', 'bedroom_2_surface', 'bedroom_3_surface',
       'bedrooms', 'co2_emission', 'cadastral_income',
       'connection_to_sewer_network', 'construction_year',
       'covered_parking_spaces', 'dining_room', 'double_glazing',
       'energy_class', 'external_reference', 'flood_zone_type', 'furnished',
       'garden_surface', 'gas_water__electricity', 'heating_type',
       'kitchen_surface', 'kitchen_type', 'latest_land_use_designation',
       'living_area', 'living_room_surface', 'number_of_frontages', 'office',
       'outdoor_parking_spaces', 'planning_permission_obtained',
       'possible_priority_purchase_right', 'primary_energy_consumption',
       'proceedings_for_breach_of_planning_regulations',
       'reference_number_of_the_epc_report', 'street_frontage_width',
       'subdivision_permit', 'surface_of_the_plot', 'surroundings_type',
       'tv_cable', 'tenement_building', 'toilets', 'website',
       'width_of_the_lot_on_the_street',
       'yearly_theoretical_total_energy_consumption', 'housenumber', 'street',
       'city', 'postal', 'lat', 'lng', 'price', 'building_condition_Good',
       'building_condition_Just renovated', 'building_condition_To be done up',
       'building_condition_To renovate', 'building_condition_To restore',
       'state_Brussels', 'state_Bruxelles', 'state_Capellen', 'state_Flanders',
       'state_Région Flamande', 'state_Région Wallonne', 'state_Vlaams Gewest',
       'state_Waals Gewest', 'state_Wallonia'],
      dtype='object')

In [83]:
#Define the mapping for categories in 'building_condition'
if 'building_condition' in data.columns:
    building_condition_mapping = {
        'To restore': 1,
        'To renovate': 2,
        'To be done up': 3,
        'Just renovated': 4,
        'Good': 5,
        'As new': 6
    }
    data['building_condition_encoded'] = data['building_condition'].map(building_condition_mapping)
    
    # Ersetze fehlende Werte mit 0 ohne inplace
    data['building_condition_encoded'] = data['building_condition_encoded'].fillna(0)
else:
    print("Column 'building_condition' does not exist in the DataFrame.")

Column 'building_condition' does not exist in the DataFrame.

In [84]:
# Convert date information: If 'available_as_of' contains a date, convert it and extract year, month, or weekday. If it's a description like "After signing the deed," use a dummy feature instead.
data['available_as_of'] = data['available_as_of'].apply(lambda x: 1 if x == 'After signing the deed' else 0)

In [85]:
# Combine bedroom areas: Sum bedroom surfaces to create 'total_bedroom_surface' as a new feature for better model insights.
data['total_bedroom_surface'] = data[['bedroom_1_surface', 'bedroom_2_surface', 'bedroom_3_surface']].sum(axis=1)

In [86]:
# Since the scale of numerical features (e.g., living_area, co2_emission, surface_of_the_plot) varies, it's beneficial to perform standardization or normalization. This improves model performance and is particularly useful for linear regression.
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
numerical_cols = ['bedroom_1_surface', 'bedroom_2_surface', 'bedroom_3_surface', 'bathrooms', 'living_area', 'surface_of_the_plot']
data[numerical_cols] = scaler.fit_transform(data[numerical_cols])

In [87]:
# Identify and handle outliers: Check for outliers in key numerical variables like price, living_area, or surface_of_the_plot that may impact regression. Consider removing values more than three standard deviations from the mean.
data = data[(data['price'] < data['price'].mean() + 3 * data['price'].std())]

In [88]:
data['building_condition'] = 'Unknown'  # Set a default value

In [89]:
building_condition_mapping = {
    'To restore': 1,
    'To renovate': 2,
    'To be done up': 3,
    'Just renovated': 4,
    'Good': 5,
    'As new': 6,
    'Unknown': 0  # Default for unknown values
}

data['building_condition_encoded'] = data['building_condition'].map(building_condition_mapping)

## Setting target variables

In [90]:
#y = data['price']

#X = data[['bedrooms', 'bathrooms', 'living_area', 'surface_of_the_plot', 'postal']]

In [91]:
# Define the target variable (price)
price = data['price']

# Feature selection and encoding
# Convert 'available_as_of' to a binary variable (1 if "After signing the deed", otherwise 0)
data['available_as_of_encoded'] = data['available_as_of'].apply(lambda x: 1 if x == 'After signing the deed' else 0)

# Sum up bedroom areas to create a total bedroom surface feature
data['total_bedroom_surface'] = data[['bedroom_1_surface', 'bedroom_2_surface', 'bedroom_3_surface']].sum(axis=1)

# Fill missing values in key features
data['construction_year'] = data['construction_year'].fillna(data['construction_year'].median())
data['building_age'] = 2023 - data['construction_year']
data['toilets'] = data['toilets'].fillna(data['toilets'].median())
data['co2_emission'] = data['co2_emission'].fillna(data['co2_emission'].median())

# Handle missing values in 'building_condition' and map categories to numerical values
data['building_condition'] = data['building_condition'].fillna('Unknown')
building_condition_mapping = {
    'To restore': 1,
    'To renovate': 2,
    'To be done up': 3,
    'Just renovated': 4,
    'Good': 5,
    'As new': 6,
    'Unknown': 0
}
data['building_condition_encoded'] = data['building_condition'].map(building_condition_mapping)

# Select core features, including the encoded 'building_condition' feature
X = data[['bedrooms', 'bathrooms', 'living_area', 'surface_of_the_plot', 'postal', 'building_condition_encoded',
          'available_as_of_encoded', 'total_bedroom_surface', 'building_age', 'toilets', 'co2_emission']]

# Apply one-hot encoding for categorical features
X = pd.concat([X, 
               pd.get_dummies(data['energy_class'], prefix='energy_class'),
               pd.get_dummies(data['kitchen_type'], prefix='kitchen_type'),
               pd.get_dummies(data['heating_type'], prefix='heating_type')
              ], axis=1)

# Preview the extended feature set
X.head()

,bedrooms,bathrooms,living_area,surface_of_the_plot,postal,building_condition_encoded,available_as_of_encoded,total_bedroom_surface,building_age,toilets,...,kitchen_type_USA installed,kitchen_type_USA semi equipped,kitchen_type_USA uninstalled,heating_type_Carbon,heating_type_Electric,heating_type_Fuel oil,heating_type_Gas,heating_type_Pellet,heating_type_Solar,heating_type_Wood
0,3.0,-0.540351,-0.503838,-0.152522,9600.0,0,0,-0.536610,70.0,2.0,...,False,False,False,False,False,True,False,False,False,False
1,4.0,-0.540351,-0.107633,1.262736,8750.0,0,0,-0.350667,36.0,1.0,...,False,False,False,False,False,True,False,False,False,False
2,5.0,1.296765,0.430608,-0.255147,2018.0,0,0,0.523596,136.0,4.0,...,False,False,False,False,False,False,True,False,False,False
3,5.0,1.296765,1.611747,-0.109058,8000.0,0,0,1.307181,190.0,4.0,...,False,False,False,False,False,False,True,False,False,False
4,1.0,-0.540351,-1.146736,-0.276880,1301.0,0,0,-0.018051,173.0,2.0,...,False,False,False,False,False,False,True,False,False,False

## Linear Regression Modell

In [93]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, RandomizedSearchCV, KFold
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.base import clone
from sklearn.model_selection import cross_val_score

# Define a custom function to perform cross-validation with different random states and cv values
def random_search_cv(X, y, random_state_range, cv_range, n_iter=10):
    best_score = -np.inf
    best_params = None
    best_model = None

    for _ in range(n_iter):
        # Randomly select random_state and cv from the given ranges
        random_state = np.random.choice(random_state_range)
        cv_folds = np.random.choice(cv_range)

        # Split the data with the current random_state
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=random_state)
        
        # Define pipeline with imputation, scaling, and linear regression
        pipeline = Pipeline([
            ('imputer', SimpleImputer(strategy='median')),
            ('scaler', StandardScaler()),
            ('regressor', LinearRegression())
        ])

        # Perform cross-validation with the current cv and pipeline
        cv = KFold(n_splits=cv_folds, shuffle=True, random_state=random_state)
        cv_scores = cross_val_score(pipeline, X_train, y_train, cv=cv, scoring='r2')
        mean_cv_score = np.mean(cv_scores)
        
        # Update best parameters if current model performs better
        if mean_cv_score > best_score:
            best_score = mean_cv_score
            best_params = {'random_state': random_state, 'cv': cv_folds}
            best_model = clone(pipeline).fit(X_train, y_train)
            
    return best_model, best_params, best_score

# Define ranges for random_state and cv
random_state_range = range(0, 100, 5)  # e.g., 0, 5, 10, ..., 95
cv_range = range(3, 11)  # e.g., 3, 4, ..., 10

# Run the custom random search
best_model, best_params, best_score = random_search_cv(X, y, random_state_range, cv_range, n_iter=10)

# Display best parameters and score
print("Best parameters found:", best_params)
print("Best cross-validated R² score:", best_score)

# Evaluate on the test set using the best model
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=best_params['random_state'])
y_pred = best_model.predict(X_test)

# Calculate error metrics
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Test Set Mean Squared Error (MSE): {mse}")
print(f"Test Set Mean Absolute Error (MAE): {mae}")
print(f"Test Set R-squared (R²): {r2}")

# Extract and print the coefficients from the model
coefficients = best_model.named_steps['regressor'].coef_
intercept = best_model.named_steps['regressor'].intercept_

# Display coefficients with feature names
print("Model Intercept:", intercept)
print("Model Coefficients:")
for feature, coef in zip(X.columns, coefficients):
    print(f"{feature}: {coef}")

Best parameters found: {'random_state': np.int64(10), 'cv': np.int64(6)}
Best cross-validated R² score: -5.962152244579192e+20
Test Set Mean Squared Error (MSE): 52260620631.030685
Test Set Mean Absolute Error (MAE): 148750.5424357745
Test Set R-squared (R²): 0.5319767733895789
Model Intercept: 472186.8885339918
Model Coefficients:
bedrooms: 13374.01457991551
bathrooms: 59810.3406952729
living_area: 121991.83603553947
surface_of_the_plot: 51332.083698701805
postal: -48828.935685771874
building_condition_encoded: 1.249792130714886e+16
available_as_of_encoded: 1.0168164894574332e+16
total_bedroom_surface: -8207.3836587138
building_age: -12196.616793022158
toilets: 26519.582496360596
co2_emission: -3091.550994773943
energy_class_A: 1.3076295743390592e+17
energy_class_A+: 3.581949731721468e+16
energy_class_A++: 1.603611711654409e+16
energy_class_B: 2.3845310750150214e+17
energy_class_C: 2.6126616663893238e+17
energy_class_C_B: 1.1340762187695712e+16
energy_class_D: 2.6998798094200614e+17
energy_class_E: 2.5163952414636672e+17
energy_class_F: 2.6110402177384493e+17
energy_class_G: 2.0982549264284422e+17
energy_class_Not specified: 1.3257094632320846e+17
kitchen_type_Hyper equipped: 53032.32623101962
kitchen_type_Installed: -269.323274874001
kitchen_type_Not installed: -32874.47184216064
kitchen_type_Semi equipped: -26401.33112576367
kitchen_type_USA hyper equipped: 27138.25269641778
kitchen_type_USA installed: -7917.070727578938
kitchen_type_USA semi equipped: 411.94187836528937
kitchen_type_USA uninstalled: -2471.1595358088516
heating_type_Carbon: -5458.861570415877
heating_type_Electric: -2722.8533923154023
heating_type_Fuel oil: -10713.234208753642
heating_type_Gas: -3034.6070928539784
heating_type_Pellet: -9589.501202146797
heating_type_Solar: -793.9825689399379
heating_type_Wood: -4431.915910459464

In [60]:
# Export the pipeline as a pickle file (tnx to utkarsh)
#import pickle
#with open('../models/best_model.pkl', 'wb') as file:
#    pickle.dump(model, file)