# Real Estate Price Prediction Project

## Importing the necessary bibliotheca

In [31]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsRegressor  # Importiere den KNN-Regressor
import pickle
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

## Load the Data

In [3]:
#data = pd.read_csv('belgian_property_prices.csv')
data = pd.read_csv('../raw_data/belgian_property_prices.csv')
#data = pd.read_csv('raw_data/belgian_property_prices.csv')
data.head()

,as_built_plan,available_as_of,basement,bathrooms,bedroom_1_surface,bedroom_2_surface,bedroom_3_surface,bedrooms,building_condition,co2_emission,...,width_of_the_lot_on_the_street,yearly_theoretical_total_energy_consumption,housenumber,street,city,postal,state,lat,lng,price
0,0.0,After signing the deed,1.0,1.0,12.0,10.0,10.0,3.0,Good,9802.0,...,11.0,NaN,30,Stationsstraat,Ronse,9600.0,Vlaams Gewest,50.743367,3.601306,275000
1,0.0,After signing the deed,1.0,1.0,15.0,11.0,11.0,4.0,Good,NaN,...,NaN,NaN,52,Wingenesteenweg,Wingene,8750.0,Vlaams Gewest,51.042146,3.302600,430000
2,NaN,After signing the deed,1.0,3.0,22.0,22.0,22.0,5.0,As new,NaN,...,6.0,NaN,157,Mechelsesteenweg,Antwerpen,2018.0,Vlaams Gewest,51.205030,4.410943,949000
3,0.0,NaN,NaN,3.0,33.0,30.0,23.0,5.0,As new,NaN,...,19.0,NaN,66,Noordzandstraat,Brugge,8000.0,Vlaams Gewest,51.206826,3.219186,2200000
4,0.0,After signing the deed,NaN,NaN,19.0,NaN,NaN,1.0,Just renovated,58.0,...,5.0,24263.0,15,Rue de l'Etoile,Wavre,1301.0,Région Wallonne,50.717062,4.577550,195000

## Exploratory Data Analysis, EDA

In [4]:
data.info()

data.describe()

data.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4770 entries, 0 to 4769
Data columns (total 54 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   as_built_plan                                   2389 non-null   float64
 1   available_as_of                                 3912 non-null   object
 2   basement                                        2083 non-null   float64
 3   bathrooms                                       4523 non-null   float64
 4   bedroom_1_surface                               3163 non-null   float64
 5   bedroom_2_surface                               3105 non-null   float64
 6   bedroom_3_surface                               2623 non-null   float64
 7   bedrooms                                        4740 non-null   float64
 8   building_condition                              4485 non-null   object
 9   co2_emission                                    1937 non-null   float64
 10  cadastral_income                                3692 non-null   float64
 11  connection_to_sewer_network                     2030 non-null   float64
 12  construction_year                               3444 non-null   float64
 13  covered_parking_spaces                          2718 non-null   float64
 14  dining_room                                     1339 non-null   float64
 15  double_glazing                                  4119 non-null   float64
 16  energy_class                                    4770 non-null   object
 17  external_reference                              4332 non-null   object
 18  flood_zone_type                                 2783 non-null   float64
 19  furnished                                       2109 non-null   float64
 20  garden_surface                                  2181 non-null   float64
 21  gas_water__electricity                          3224 non-null   float64
 22  heating_type                                    4136 non-null   object
 23  kitchen_surface                                 2675 non-null   float64
 24  kitchen_type                                    3960 non-null   object
 25  latest_land_use_designation                     2245 non-null   object
 26  living_area                                     4702 non-null   float64
 27  living_room_surface                             3015 non-null   float64
 28  number_of_frontages                             4455 non-null   float64
 29  office                                          1444 non-null   float64
 30  outdoor_parking_spaces                          2355 non-null   float64
 31  planning_permission_obtained                    1540 non-null   float64
 32  possible_priority_purchase_right                2198 non-null   float64
 33  primary_energy_consumption                      4571 non-null   float64
 34  proceedings_for_breach_of_planning_regulations  1742 non-null   float64
 35  reference_number_of_the_epc_report              4770 non-null   object
 36  street_frontage_width                           2096 non-null   float64
 37  subdivision_permit                              1814 non-null   float64
 38  surface_of_the_plot                             4563 non-null   float64
 39  surroundings_type                               2274 non-null   object
 40  tv_cable                                        1460 non-null   float64
 41  tenement_building                               4723 non-null   float64
 42  toilets                                         4348 non-null   float64
 43  website                                         3963 non-null   object
 44  width_of_the_lot_on_the_street                  1990 non-null   float64
 45  yearly_theoretical_total_energy_consumption     1813 non-null   float64
 46  housenumber                                     4657 non-null   object
 47  street                                          4685 non-null   object
 48  city                                            4721 non-null   object
 49  postal                                          4737 non-null   float64
 50  state                                           4728 non-null   object
 51  lat                                             4737 non-null   float64
 52  lng                                             4737 non-null   float64
 53  price                                           4770 non-null   int64
dtypes: float64(39), int64(1), object(14)
memory usage: 2.0+ MB

Index(['as_built_plan', 'available_as_of', 'basement', 'bathrooms',
       'bedroom_1_surface', 'bedroom_2_surface', 'bedroom_3_surface',
       'bedrooms', 'building_condition', 'co2_emission', 'cadastral_income',
       'connection_to_sewer_network', 'construction_year',
       'covered_parking_spaces', 'dining_room', 'double_glazing',
       'energy_class', 'external_reference', 'flood_zone_type', 'furnished',
       'garden_surface', 'gas_water__electricity', 'heating_type',
       'kitchen_surface', 'kitchen_type', 'latest_land_use_designation',
       'living_area', 'living_room_surface', 'number_of_frontages', 'office',
       'outdoor_parking_spaces', 'planning_permission_obtained',
       'possible_priority_purchase_right', 'primary_energy_consumption',
       'proceedings_for_breach_of_planning_regulations',
       'reference_number_of_the_epc_report', 'street_frontage_width',
       'subdivision_permit', 'surface_of_the_plot', 'surroundings_type',
       'tv_cable', 'tenement_building', 'toilets', 'website',
       'width_of_the_lot_on_the_street',
       'yearly_theoretical_total_energy_consumption', 'housenumber', 'street',
       'city', 'postal', 'state', 'lat', 'lng', 'price'],
      dtype='object')

## Preprocessing

In [5]:
import pandas as pd

data = pd.read_csv('../raw_data/belgian_property_prices.csv')

data_raw_backup = data.copy()

data_raw_backup.to_csv('belgian_property_prices_backup.csv', index=False)

data.head()

,as_built_plan,available_as_of,basement,bathrooms,bedroom_1_surface,bedroom_2_surface,bedroom_3_surface,bedrooms,building_condition,co2_emission,...,width_of_the_lot_on_the_street,yearly_theoretical_total_energy_consumption,housenumber,street,city,postal,state,lat,lng,price
0,0.0,After signing the deed,1.0,1.0,12.0,10.0,10.0,3.0,Good,9802.0,...,11.0,NaN,30,Stationsstraat,Ronse,9600.0,Vlaams Gewest,50.743367,3.601306,275000
1,0.0,After signing the deed,1.0,1.0,15.0,11.0,11.0,4.0,Good,NaN,...,NaN,NaN,52,Wingenesteenweg,Wingene,8750.0,Vlaams Gewest,51.042146,3.302600,430000
2,NaN,After signing the deed,1.0,3.0,22.0,22.0,22.0,5.0,As new,NaN,...,6.0,NaN,157,Mechelsesteenweg,Antwerpen,2018.0,Vlaams Gewest,51.205030,4.410943,949000
3,0.0,NaN,NaN,3.0,33.0,30.0,23.0,5.0,As new,NaN,...,19.0,NaN,66,Noordzandstraat,Brugge,8000.0,Vlaams Gewest,51.206826,3.219186,2200000
4,0.0,After signing the deed,NaN,NaN,19.0,NaN,NaN,1.0,Just renovated,58.0,...,5.0,24263.0,15,Rue de l'Etoile,Wavre,1301.0,Région Wallonne,50.717062,4.577550,195000

In [6]:
# Replace missing values for specified columns with the median
for col in ['bedroom_1_surface', 'bedroom_2_surface', 'bedroom_3_surface', 'bathrooms', 'bedrooms']:
    data[col] = data[col].fillna(data[col].median())

In [8]:
# Convert categorical variables with a few well-defined categories into numerical form using One-Hot Encoding.
# This is particularly suitable for variables like building_condition, state, and possibly city if you don't want to differentiate cities too strongly.
data = pd.get_dummies(data, columns=['building_condition', 'state'], drop_first=True)

In [10]:
#Define the mapping for categories in 'building_condition'
if 'building_condition' in data.columns:
    building_condition_mapping = {
        'To restore': 1,
        'To renovate': 2,
        'To be done up': 3,
        'Just renovated': 4,
        'Good': 5,
        'As new': 6
    }
    data['building_condition_encoded'] = data['building_condition'].map(building_condition_mapping)
    
    # Ersetze fehlende Werte mit 0 ohne inplace
    data['building_condition_encoded'] = data['building_condition_encoded'].fillna(0)
else:
    print("Column 'building_condition' does not exist in the DataFrame.")

Column 'building_condition' does not exist in the DataFrame.

In [11]:
# Convert date information: If 'available_as_of' contains a date, convert it and extract year, month, or weekday. If it's a description like "After signing the deed," use a dummy feature instead.
data['available_as_of'] = data['available_as_of'].apply(lambda x: 1 if x == 'After signing the deed' else 0)

In [12]:
# Combine bedroom areas: Sum bedroom surfaces to create 'total_bedroom_surface' as a new feature for better model insights.
data['total_bedroom_surface'] = data[['bedroom_1_surface', 'bedroom_2_surface', 'bedroom_3_surface']].sum(axis=1)

In [13]:
# Since the scale of numerical features (e.g., living_area, co2_emission, surface_of_the_plot) varies, it's beneficial to perform standardization or normalization. This improves model performance and is particularly useful for linear regression.
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
numerical_cols = ['bedroom_1_surface', 'bedroom_2_surface', 'bedroom_3_surface', 'bathrooms', 'living_area', 'surface_of_the_plot']
data[numerical_cols] = scaler.fit_transform(data[numerical_cols])

In [14]:
# Identify and handle outliers: Check for outliers in key numerical variables like price, living_area, or surface_of_the_plot that may impact regression. Consider removing values more than three standard deviations from the mean.
data = data[(data['price'] < data['price'].mean() + 3 * data['price'].std())]

In [15]:
data['building_condition'] = 'Unknown'  # Set a default value

In [16]:
building_condition_mapping = {
    'To restore': 1,
    'To renovate': 2,
    'To be done up': 3,
    'Just renovated': 4,
    'Good': 5,
    'As new': 6,
    'Unknown': 0  # Default for unknown values
}

data['building_condition_encoded'] = data['building_condition'].map(building_condition_mapping)

## Setting target variables

In [34]:
# Define target and select features

# Define target variable
price = data['price']

# Encode 'available_as_of' as a binary variable
data['available_as_of_encoded'] = data['available_as_of'].apply(lambda x: 1 if x == 'After signing the deed' else 0)

# Create 'total_bedroom_surface' by summing bedroom surface columns
data['total_bedroom_surface'] = data[['bedroom_1_surface', 'bedroom_2_surface', 'bedroom_3_surface']].sum(axis=1)

# Handle missing values without using inplace=True to avoid FutureWarnings
data['construction_year'] = data['construction_year'].fillna(data['construction_year'].median())
data['building_age'] = 2023 - data['construction_year']

data['toilets'] = data['toilets'].fillna(data['toilets'].median())
data['co2_emission'] = data['co2_emission'].fillna(data['co2_emission'].median())

In [35]:
# Encode 'building_condition'
building_condition_mapping = {'To restore': 1, 'To renovate': 2, 'To be done up': 3, 'Just renovated': 4, 'Good': 5, 'As new': 6, 'Unknown': 0}
data['building_condition_encoded'] = data['building_condition'].fillna('Unknown').map(building_condition_mapping)

# Core features and one-hot encoding
X = pd.concat([
    data[['bedrooms', 'bathrooms', 'living_area', 'surface_of_the_plot', 'postal', 'building_condition_encoded',
          'available_as_of_encoded', 'total_bedroom_surface', 'building_age', 'toilets', 'co2_emission']],
    pd.get_dummies(data[['energy_class', 'kitchen_type', 'heating_type']])
], axis=1)

## KNN Model

In [36]:
# Split data and create KNN pipeline
X_train, X_test, y_train, y_test = train_test_split(X, price, test_size=0.2, random_state=42)
pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler()),
    ('knn', KNeighborsRegressor(n_neighbors=5))
])

In [37]:
# Train and evaluate
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)
mse, mae, r2 = mean_squared_error(y_test, y_pred), mean_absolute_error(y_test, y_pred), r2_score(y_test, y_pred)

print(f"MSE: {mse}, MAE: {mae}, R²: {r2}")

MSE: 46146848286.67162, MAE: 140734.9606837607, R²: 0.5409892243422564

## The end

In [18]:
# Export the pipeline as a pickle file (tnx to utkarsh)
#import pickle
#with open('../models/best_model.pkl', 'wb') as file:
#    pickle.dump(model, file)